/**
 * @description       : 
 * @author            : juan.parra@unosquare.com
 * @group             : 
 * @last modified on  : 18-05-2022
 * @last modified by  : juan.parra@unosquare.com
**/

TriggerHandler.bypass('ContactTiggerHandler');
Contact con = new Contact(lastName = 'Pepe6', Birthdate = daste.TODAY(), AccountId = '001IY000002Y09TYAS');
insert con;

TriggerHandler.clearBypass('ContactTiggerHandler');
